# https://leetcode.com/problems/valid-palindrome-ii/

def isPalindrome(s):

    start = 0
    end = len(s) - 1

    while start <= end:
        if s[start] == s[end]:
            start += 1
            end -= 1
        else:
            return False
    
    return True

# TLE
def validPalindrome(s):
    # check the string given itself is a palindrome or not
    # if the given string is not a plaindrome, try deleting each character and check if its a palindrome or not

    if isPalindrome(s):
        return True

    for i in range(len(s)):
        new = s[:i] + s[i+1:]
        if isPalindrome(new):
            return True
    
    return False

def validPalindrome2(s):
    # check if the given string itself is a palindrome
    # Else, use two pointer algorithm, to get the position where the palindromicity is broken (start and end)
    # Try deleting s[start]/s[end] and check if it is a palindrome
    
    if isPalindrome(s):
        return True

    start = 0
    end = len(s) - 1

    while start <= end:
        if s[start] == s[end]:
            start += 1
            end -= 1
        else:
            # string with s[start] deleted
            temp1 = s[:start] + s[start+1:]
            temp2 = s[:end] + s[end+1:]

            if isPalindrome(temp1):
                return True
            elif isPalindrome(temp2):
                return True
            else:
                return False

def main():
    s = "ipjiabbborwutgpnvarhbhjflnfztggysbomzpesulanxwtmahpitzxrscmyjyatyflapdkcsjmmvuvpkrevsxlcrkbqnrqcmwltqjbewlmmslzcgrusgfthllruivocaaoiuyqduwyqkcsoohanzxryudthnblqidmvnqlqnurqdliebsezgdlzskhxzzvenxwmjokyunloqagyoklswajycvdijniolcpvslvemumzzzdgzwzfskkztjxmfyltznajikmdebspxvxcxvigpzvwipajgtxdkztaitgukitljtwjsuhdjbtkqmtvpguqoxxndvwuzyjhntlopuwbnbpxymbfnpnurgfgwnhlplzpnnpqdbpygrhswpqyaffwazvkuxlvhtuaaxgcshnmsexjmofonbzbmeshcjjzwtemequcjcmtswahgzkktgnvlsyrxoqwsenclwckwkmtrkmxgkfdgvimyejtitcugynhymonndswxgjlcimyrnlpzxpdbmzqfjhjyikrejjlwnxvksoiucyvjtuzptxwvxdssudxxmwmrgbocdhqbdssbbanwmnflqedgtzjqobgofvxeiwbggadbgudvsdatarbzjxtccraqxemsxfzqlwqislkbuneoymhqhrzhczhteqauvcaacmynrxfmrndgdudjcwdcirujjutsiunfjumgxfjgbpegellqwcwbraekfaxvrpveswjrhuinqgmujnorstfvptoceghvafewlhaujmonvvtmthibbotzcuqhfladmdrtbfsrnrjkilqxqoyjziwijuozdklzbrijkdvxkgcshbylqkbeqrwrigiyyvfeiaqwavqxyvhzbescjqpqjaqaqypwhztukkbdwgojdqiqlvygxvioubygirwmlfrqgylohfuodcvfpaqruiwzcglvrqmtwebxorngbscaxdfxguxhfzkikumxscrhlsbczsfptsatmdlxjziosjvxmlnrysfgsyouzrsxddseoncqpmwerajhkzxvxucxlltllrplhbehpmjxpkoghqxwcfdvwuwogidkedwpilwpaqetypuzarvnrupqtxxrzjscdvkawcgezftvusddqhwszadragxqpgwhhugvykxytgmtsivuxfyjuslgqkbnpvtgpqyiimpzfwfkcdssskbmfehigeqxdzprylbnnjlawjwpaxnfanufzhpcuzotfayrnheqppddirlsdjxrgujtoobmiwdylfbfzdcqygjpsupepqmcmvyuohyqywaszwiiabfdjngklkcwiwtdhkvwlpdmilrjvzemfxpvfzavejxgultgulvigqmxfsecojlpzghmookwxwytsxuadbpkdfjuzicharfhnytysuriecrwvdnguhzapktlzxcfhuacclgdcbkdrorfylzeybsdmqiymwjvpsxxegeegcfkrnlvmhgvenoxnprsswshskjwazrocohpliayyagaygmdlrxaomgvarzdavayurbrktoxblvntzscehdyyzcdbjhlrqjlyteqcfuqoihdwvegobzpqxdwcuoezglbrtlofjnedqfjnoraglzxfghbxaieavytzirsdscilscsbocfdthbdsflsflqibkmtapvaukoqbmodlgewcrqmjdzecllqmgpnfindnaevogrpbzzyrbdrvqlpgtlnrmrwhfkrqrayrlbqcfojjpydogiryxmxjkljbyrxsfikmkfvxyyaoygzxiswgaodxlebnncwuywsqphrxqcioxdfjmkzpfjytroajttdlaegdsvnwfemagxcysnqdjoeagfvgdvuwonxynaahdqegykcwgevzrfiwgvizmadhodejgppegcjwrwxvoszfbfmpigqwyedebsylpicvvvjvqnkwtfdycslvjhoxqhmvfzwdgnfksaoaanhackimdjxjyyxpuyierdlwcgxxzxqnfexqjwuxbbgbzndrcgvzrdocoahclawkhvxitexpyybrsxaulpvumygggyxollkadoaucnqnmygsyqjxjagdtqjrmgfsgofocxgijekwovcyecqpghtezymqidgrmlzzkozxpgnxfoczemsfqltmpgqbmsokwdsqbhifdojrvkraoysmaxsnetkiqiduvnqkhmxlnvjwchiolixwzyiziunzudacfyfbovnxhfkzedkfmwpuxgaqhortuooducaujqhgoqnhiptxvayizefjivkphqbsngwaijczssrftvilmcbnotvibznbjzojgaopljdfcmpuaeaasnpduilohcgfocjljijwqallfcftebxssxtkcgcltvjhzsgfczillatgyzeoydazmagbrupzajkuhfgcetgwqenajijtoxnffkyxqruyuxywehdtyrtivbrgnmvasfwtpzfhzsnoclknqkhwklepciijaoykvivmidchplymzbeyyltmsnddymvieoydsqzypnmsdyzgcuujzqqtgxybhsliselfamhnemjmkiufsnqevdtjgggakeygnpypbbjvdayqppajprhsfbehdjtahrwlxkqvqsimbvcbwuyrjksbnkteaoqhdzkaimkteoxitalzvzjrdeenrtbtrbppjjajqnzuizvdgmlgxsbyjwzxfsqagutkfbzkzezdfnjlgxrlvpymbpdgzbneglootnpnclrgnkcmtsaivetdnkfkkowgmsbvvrrfdscxmzybygaphvzpocjpbkouydoszcingtkreqgmjudvjgjhaylurngmemamzumzvhxnoqzvmmdipocgzacelrdodpbfpupzwffbqzjwcmieydvdkvgiashklljmnijdlchtxmofuhvzkihzlroveuqparrbmlgazfzonvmvojffuzhlzthmbzzsqetkbwfeyphmsetjeoaktjrmmyuexrlyezvsxmxgmntnlwtqsqfiacwkdjmltmgrkxoijawdypkegrulxpbpiknovpswibodsuqavszcttkchdsobwvfngqxzpidqwvlwzafswiattvwnniboldikuxwzvmfmqlpnydfjyvipmudkqmbrlmthyddnbkyazqrydxmbtvvooluumrrfbtkqqhunitsmndoikcvtijzurhfprdjlclnnfvwkovbbbzyrcbszlgrjswhvuqwevhlrspsoypxdocxjigwaotioazvsnpaebvantycbpntvtzfzyjxupumdxnzqxxeavdloumekxqzxlabdkdqhydtzbpjcszkppjvaaotjtyhnffibvdzdugupuqcqcjudporpyqykbllbjgtunewqoeuqdufwjbpgiroqsgotrkqxwayrucfzetmzbzazwdfmebnrelkxyfwbifzajgxodbwryzyxacgtmsmvdqmvghyrtbpohysqpmzoxnldneajwrkzzbemrttgqslyqloonosogakddsopvrneksguqnzkxwcmtbncninwczyuqexhfcpvqhogrbaaoanpabknwfdjfttuphlpeqmqghmtwhillyhxeckxleyfvjvwhalffdgdhjqqtonbvlxqywcmxeolaaxxgmkdixrkyrhiltsdpzqddkirshtmcvdifizzgnyxfckxegiowtawgstkljnjxbtgdisekpkaotioditojivkupiipomnrkytnoiirvszjbdcovbmfpymagauofnrqltszswiykkokrixfenqznfbrdxsipvqxyqpnhlwtusnvbbyizqzlwthzkmclnkndlcgeqjohzfrtuxxfkdjdeyawiresqkbkhwqsyajiphhnvqjromrvetbdhqbrojdnoqcachzmnnozmjvrglpbqedxwcvwfnupnvmgnkylkuuyrvkhfwrylwbvutekovgqsnhqzveqjtgfpnmytkmwfjcjncrcazmbkegmzesfexozjrjirmfszfciraxsilnxydjbemkdapxzagzbqeufubzcikcvrrqjgtsiqtvczgegwlugfjljjqnobcyyysdfpsdgplirugwobatiwstojbtsmhdxlljpgbbawerlxpzsupgzybyffjrlxogahvtyhigtpcmexvgbxryymmpwmmkndxzuuirxuuduvqpbaywnqqjqhxeoxaltncwswgeidmdfcxrfrycwfqklfjaucuuazmddgaggeeeacscupeqvuiaeembweabwfvkumfpebchagzlqvgzzwgbeztxvvicoquffsiuhbfupneikkekmklgxrrweyaahzzukuauctcevrsxvxpxaswwrkespnhfqoqtxxlicppldbtilqzhsvgzwqhogggeogovlaclygljdwxoalmebnacmyxxwhytnvydlhaqgelhvblomycggcttfsgpcwiihpnpskocxoqhqddnqttsdqredayysxsxhntxlnaolfnklpjgttxssmekttsktqhqbkpyhmmribrvamxmhvensenhorpktppydgvlvzkhysvtbylyfjvioqydtanyidhqyasfxvvhribyzcmndlcdlwaktnlzkzlfhcnvhhfnoqivdcasvgnxorequzonywuhrvzwlwdpvgafgbwyhwqtogjgnupmrgxeokkpxuddsbdtjymcycnosmwoqonlzsbwzwmlqyrwzcneuywvwiaoclzrzyvacngjuuzkmsxubkcjunyanmwegplprwtrgqkfgwjuflzywglyewunsudzjbjcuonevldylbaibrbfbhctdconoohpmvwmeozbgcjqzmsqdltgovzuhyxnvrhbldabjooigfzealnrutqikeisljdozhjzmnrwdqqdldpsltgtcjmlhuirzinefgvyvtyldclwuwrqsngtwjzuvsjitjovqsxgmwwcaetefbxowgultdlgxccbtrzmtqkpyvqipcrrkuukrrcpiqvypkqtmzrtbccxgldtlugwoxbfeteacwwmgxsqvojtijsvuzjwtgnsqrwuwlcdlytvyvgfenizriuhlmjctgtlspdldqqdwrnmzjhzodjlsiekiqturnlaezfgioojbadlbhrvnxyhuzvogtldqsmzqjcgbzoemwvmphoonocdtchbfbrbiablydlvenoucjbjzdusnuweylgwyzlfujwgfkqgrtwrplpgewmnaynujckbuxsmkzuujgncavyzrzlcoaiwvwyuenczwryqlmwzwbszlnoqowmsoncycmyjtdbsdduxpkkoexgrmpungjgotqwhywbgfagvpdwlwzvrhuwynozuqeroxngvsacdviqonfhhvnchflzkzlntkawldcldnmczybirhvvxfsayqhdiynatdyqoivjfylybtvsyhkzvlvgdypptkprohnesnevhmxmavrbirmmhypkbqhqtksttkemssxttgjplknfloanlxtnhxsxsyyaderqdsttqnddqhqoxcokspnphiiwcpgsfttcggcymolbvhlegqahldyvntyhwxxymcanbelaoxwdjlgylcalvogoegggohqwzgvshzqlitbdlppcilxxtqoqfhnpsekrwwsaxpxvxsrvectcuukuzzhaayewrrxglkmkekkienpufbhuisffuqocivvxtzebgwzzgvqlzgahcbepfmukvfwbaewbmeeaiuvqepucscaeeeggagddmzauucuajflkqfwcyrfrxcfdmdiegwswcntlaxoexhqjqqnwyabpqvuduuxriuuzxdnkmmwpmmyyrxbgvxemcptgihytvhagoxlrjffybyzgpuszpxlrewabbgpjllxdhmstbjotswitabowgurilpgdspfdsyyycbonqjjljfgulwgegzcvtqistgjqrrvckiczbufueqbzgazxpadkmebjdyxnlisxaricfzsfmrijrjzoxefsezmgekbmzacrcnjcjfwmktymnpfgtjqevzqhnsqgvoketuvbwlyrwfhkvryuuklykngmvnpunfwvcwxdeqbplgrvjmzonnmzhcacqondjorbqhdbtevrmorjqvnhhpijaysqwhkbkqseriwayedjdkfxxutrfzhojqegcldnknlcmkzhtwlzqziybbvnsutwlhnpqyxqvpisxdrbfnzqnefxirkokkyiwszstlqrnfouagamypfmbvocdbjzsvriiontykrnmopiipukvijotidoitoakpkesidgtbxjnjlktsgwatwoigexkcfxyngzzifidvcmthsrikddqzpdstlihrykrxidkmgxxaaloexmcwyqxlvbnotqqjhdgdfflahwvjvfyelxkcexhyllihwtmhgqmqeplhputtfjdfwnkbapnaoaabrgohqvpcfhxequyzcwnincnbtmcwxkznqugskenrvposddkagosonoolqylsqgttrmebzzkrwjaendlnxozmpqsyhopbtryhgvmqdvmsmtgcaxyzyrwbdoxgjazfibwfyxklernbemfdwzazbzmtezfcuryawxqkrtogsqorigpbjwfudqueoqwenutgjbllbkyqypropdujcqcqupugudzdvbiffnhytjtoaavjppkzscjpbztdyhqdkdbalxzqxkemuoldvaexxqznxdmupuxjyzfztvtnpbcytnavbeapnsvzaoitoawgijxcodxpyospsrlhvewquvhwsjrglzsbcryzbbbvokwvfnnlcljdrpfhruzjitvckiodnmstinuhqqktbfrrmuuloovvtbmxdyrqzaykbnddyhtmlrbmqkdumpivyjfdynplqmfmvzwxukidlobinnwvttaiwsfazwlvwqdipzxqgnfvwbosdhckttczsvaqusdobiwspvonkipbpxlurgekpydwajioxkrgmtlmjdkwcaifqsqtwlntnmgxmxsvzeylrxeuymmrjtkaoejtesmhpyefwbkteqszzbmhtzlhzuffjovmvnozfzaglmbrrapquevorlzhikzvhufomxthcldjinmjllkhsaigvkdvdyeimcwjzqbffwzpupfbpdodrlecazgcopidmmvzqonxhvzmuzmamemgnrulyahjgjvdujmgqerktgniczsodyuokbpjcopzvhpagybyzmxcsdfrrvvbsmgwokkfkndteviastmckngrlcnpntoolgenbzgdpbmypvlrxgljnfdzezkzbfktugaqsfxzwjybsxglmgdvziuznqjajjppbrtbtrneedrjzvzlatixoetkmiakzdhqoaetknbskjryuwbcvbmisqvqkxlwrhatjdhebfshrpjappqyadvjbbpypngyekagggjtdveqnsfuikmjmenhmaflesilshbyxgtqqzjuucgzydsmnpyzqsdyoeivmyddnsmtlyyebzmylphcdimvivkyoajiicpelkwhkqnklconszhfzptwfsavmngrbvitrytdhewyxuyurqxykffnxotjijaneqwgtecgfhukjazpurbgamzadyoezygtallizcfgszhjvtlcgcktxssxbetfcfllaqwjijljcofgcholiudpnsaaeaupmcfdjlpoagjozjbnzbivtonbcmlivtfrsszcjiawgnsbqhpkvijfeziyavxtpihnqoghqjuacudooutrohqagxupwmfkdezkfhxnvobfyfcaduznuiziyzwxiloihcwjvnlxmhkqnvudiqiktensxamsyoarkvrjodfihbqsdwkosmbqgpmtlqfsmezcofxngpxzokzzlmrgdiqmyzethgpqceycvowkejigxcofogsfgmrjqtdgajxjqysgymnqncuaodaklloxygggymuvpluaxsrbyypxetixvhkwalchaocodrzvgcrdnzbgbbxuwjqxefnqxzxxgcwldreiyupxyyjxjdmikcahnaaoaskfngdwzfvmhqxohjvlscydftwknqvjvvvciplysbedeywqgipmfbfzsovxwrwjcgeppgjedohdamzivgwifrzvegwckygeqdhaanyxnowuvdgvfgaeojdqnsycxgamefwnvsdgealdttjaortyjfpzkmjfdxoicqxrhpqswyuwcnnbelxdoagwsixzgyoayyxvfkmkifsxrybjlkjxmxyrigodypjjofcqblryarqrkfhwrmrnltgplqvrdbryzzbprgoveandnifnpgmqllcezdjmqrcwegldombqokuavpatmkbiqlfslfsdbhtdfcobscslicsdsriztyvaeiaxbhgfxzlgaronjfqdenjfoltrblgzeoucwdxqpzbogevwdhioqufcqetyljqrlhjbdczyydhecsztnvlbxotkrbruyavadzravgmoaxrldmgyagayyailphocorzawjkshswssrpnxonevghmvlnrkfcgeegexxspvjwmyiqmdsbyezlyfrordkbcdglccauhfcxzltkpazhugndvwrceirusytynhfrahcizujfdkpbdauxstywxwkoomhgzpljocesfxmqgivlugtlugxjevazfvpxfmezvjrlimdplwvkhdtwiwcklkgnjdfbaiiwzsawyqyhouyvmcmqpepuspjgyqcdzfbflydwimbootjugrxjdslriddppqehnryaftozucphzfunafnxapwjwaljnnblyrpzdxqegihefmbksssdckfwfzpmiiyqpgtvpnbkqglsujyfxuvistmgtyxkyvguhhwgpqxgardazswhqddsuvtfzegcwakvdcsjzrxxtqpurnvrazupyteqapwlipwdekdigowuwvdfcwxqhgokpxjmphebhlprlltllxcuxvxzkhjarewmpqcnoesddxsrzuoysgfsyrnlmxvjsoizjxldmtastpfszcbslhrcsxmukikzfhxugxfdxacsbgnroxbewtmqrvlgczwiurqapfvcdoufholygqrflmwrigybuoivxgyvlqiqdjogwdbkkutzhwpyqaqajqpqjcsebzhvyxqvawqaiefvyyigirwrqebkqlybhscgkxvdkjirbzlkdzoujiwizjyoqxqlikjrnrsfbtrdmdalfhqucztobbihtmtvvnomjuahlwefavhgecotpvftsronjumgqniuhrjwsevprvxafkearbwcwqllegepbgjfxgmujfnuistujjuricdwcjdudgdnrmfxrnymcaacvuaqethzchzrhqhmyoenubklsiqwlqzfxsmexqarcctxjzbratadsvdugbdaggbwiexvfogboqjztgdeqlfnmwnabbssdbqhdcobgrmwmxxdussdxvwxtpzutjvycuioskvxnwljjerkiyjhjfqzmbdpxzplnrymicljgxwsdnnomyhnyguctitjeymivgdfkgxmkrtmkwkcwlcneswqoxryslvngtkkzghawstmcjcuqemetwzjjchsembzbnofomjxesmnhscgxaauthvlxukvzawffayqpwshrgypbdqpnnpzlplhnwgfgrunpnfbmyxpbnbwupoltnhjyzuwvdnxxoqugpvtmqktbjdhusjwtjltikugtiatzkdxtgjapiwvzpgivxcxvxpsbedmkijanztlyfmxjtzkksfzwzgdzzzmumevlsvpcloinjidvcyjawslkoygaqolnuykojmwxnevzzxhkszldgzesbeildqrunqlqnvmdiqlbnhtduyrxznahoosckqywudqyuioaacoviurllhtfgsurgczlsmmlwebjqtlwmcqrnqbkrclxsverkpvuvmmjsckdpalfytayjymcsrxztiphamtwxnalusepzmobsyggtzfnlfjhbhravnpgtuwrobbbaijpi"
    print(validPalindrome2(s))

main()